apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-securitycontext
spec:
  rules:
  - name: add-runasgroup
    match:
      any:
      - resources:
          kinds:
          - Pod
    context:
    - name: value
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: metadata.annotations."odencluster.com/primary-gid" || 'empty'
    - name: parse
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: split(metadata.annotations."odencluster.com/primary-gid",'/') | [0] | to_number(@)
    preconditions:
      all:
      - key: "{{ value }}"
        operator: NotEquals
        value: empty
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            +(runAsGroup): "{{ parse }}"
